name: proba CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 19, 20]

    steps:
    - name: Clone the git repo
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install node modules
      run: npm install

    - name: Start node js app in the background
      run: npm start &

    - name: Wait for the server to be ready
      run: npx wait-on http://localhost:3000

    - name: Run tests
      run: npm test